#!/usr/bin/env bash

# Install command-line tools using Homebrew.
# TODO Swich to Brewfile

#Xcode CLI tools
xcode-select --install

#Install brew
which -s brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

brew tap homebrew/cask-fonts
brew tap thoughtbot/formulae

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names

brew install bash
brew install bash-completion2
brew instal zsh
brew install wget --with-iri
brew install gnupg
brew install vim --with-override-system-vi
brew install grep
brew install openssh
brew install tmux
brew install screen
brew install gmp
brew install ack
brew install git
brew install git-lfs
brew install gs
brew install imagemagick --with-webp
brew install p7zip
brew install pigz
brew install pv
brew install rename
brew install rlwrap
brew install ssh-copy-id
brew install tree
brew install vbindiff
brew install ripgrep
brew install the_silver_searcher
brew install fzf
brew install rcm
brew install diff-so-fancy
brew install catimg
brew install exa
brew cask install font-hack-nerd-font


# Remove outdated versions from the cellar.
brew cleanup
