#!/usr/bin/env bash

# Install command-line tools using Homebrew.
# TODO Swich to Brewfile

#Xcode CLI tools
xcode-select --install

#Install brew
which -s brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

brew tap homebrew/cask-fonts
brew tap thoughtbot/formulae

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names
brew install wget --with-iri
brew install vim --with-override-system-vi
brew install imagemagick --with-webp

formulas=(
  ack
  apktool
  asciidoctor
  bash
  catimg
  colordiff
  colortail
  coreutils
  cowsay
  csvkit
  ctop
  dateutils
  dex2jar
  diff-so-fancy
  entr
  exa
  exiftool
  fd
  feh
  ffmpeg
  fpp
  fswatch
  fzf
  git
  git-extras
  git-lfs
  git-open
  git-plus
  git-quick-stats
  git-recent
  git-smartlog
  git-standup
  glow
  gmp
  gnu-sed
  gnupg
  gnutls
  grep
  gs
  htop
  httpie
  jq
  kscript
  ktlint
  md5sha1sum
  ncdu
  neofetch
  noti
  num-utils
  openssh
  p7zip
  pandoc
  pidcat
  pigz
  pokemonsay
  ponysay
  prettyping
  pv
  rcm
  rename
  ripgrep
  rlwrap
  rust
  screen
  spark
  ssh-copy-id
  terminal-notifier
  the_silver_searcher
  tmux
  tree
  vbindiff
  xidel
  xmlstarlet
  yq
  zsh
)
echo $formulas | tr ' ' '\n' | xargs brew install

brew cask install font-hack-nerd-font
brew install --cask anybar

brew tap isacikgoz/taps
brew install gitbatch

# Remove outdated versions from the cellar.
brew cleanup
