#!/usr/bin/env bash

OS=$(uname -s)
REPO="$(dirname $0)/.."
pushd $REPO
git submodule update --init --recursive
if [ $OS = "Darwin" ]; then
    echo "Install OSX defaults"
    source ./bootstrap/brew
else
    # assuming Debian based for now.
    echo "Install Linux defaults"
    sudo apt update
    cat ./bootstrap/apt | xargs sudo apt install
fi

# Backs up old files
[ -f ~/.zshrc ] && [ ! -f ~/.zshrc.local ] && mv ~/.zshrc ~/.zshrc.local
[ -f ~/.gitconfig ] && [ ! -f ~/.gitconfig.local ] && mv ~/.gitconfig ~/.gitconfig.local
[ -f ~/.tmux.conf ] && [ ! -f ~/.tmux.conf.local ] && mv ~/.tmux ~/.tmux.conf.local

echo "Running rcup, make take a few minutes..."
rcup
popd

echo "Install Rust libraries"
cat ./bootstrap/cargo | xargs cargo install

echo "Install NPM libraries"
cat ./bootstrap/npm | xargs npm -g install

echo "Install Go libraries"
source ./bootstrap/go

echo "Install Python3 libraries"
cat ./bootstrap/pip | xargs pip3 install

echo "Install Python libraries"
cat ./bootstrap/pip | xargs pip install

echo "finished! restart shell."
