#!/usr/bin/env bash

[[ "$SHELL" == *"zsh"* ]] || (echo "Please switch login shell to ZSH" && exit 1)
git --version > /dev/null || (echo "Please install git" && exit 2)

OS=$(uname -s)
REPO="$(dirname $0)/.."
pushd $REPO
git submodule update --init --recursive
if [ $OS = "Darwin" ]; then
    echo "Install OSX defaults"
    source ./bootstrap/brew

    if [ -d ~/.hammerspoon ]; then
        echo "Existing Hammerspoon scripts found"
        exit 3
    elif [ ! -L ~/.hammerspoon ]; then
        ln -s ./hammerspoon ~/.hammerspoon
    fi
else
    # assuming Debian based for now.
    echo "Install Linux defaults"
    sudo apt update
    cat ./bootstrap/apt | xargs sudo apt install --assume-yes
fi

# Backs up old files
[ ! -L ~/.zshrc ] && [ -f ~/.zshrc ] && [ ! -f ~/.zshrc.local ] && mv ~/.zshrc ~/.zshrc.local
[ ! -L ~/.gitconfig ] && [ -f ~/.gitconfig ] && [ ! -f ~/.gitconfig.local ] && mv ~/.gitconfig ~/.gitconfig.local
[ ! -L ~/.tmux.conf ] && [ -f ~/.tmux.conf ] && [ ! -f ~/.tmux.conf.local ] && mv ~/.tmux ~/.tmux.conf.local

echo "Install OMZ, plugins, & themes"
if [ ! -f ~/.oh-my-zsh/oh-my-zsh.sh ]; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
source bin/install_omz_plugin
for PLUGIN in `cat ./bootstrap/omz-plugins`; do install_omz_plugin $PLUGIN; done;
for THEME in `cat ./bootstrap/omz-themes`; do install_omz_theme $THEME; done;

echo "Running rcup, make take a few minutes..."
rcup
popd

echo "Install Rust libraries"
cat ./bootstrap/cargo | xargs cargo install

echo "Install NPM libraries"
cat ./bootstrap/npm | xargs npm -g install

echo "Install Go libraries"
source ./bootstrap/go

echo "Install Python3 libraries"
cat ./bootstrap/pip | xargs pip3 install

echo "Install Python libraries"
cat ./bootstrap/pip | xargs pip install

echo "finished! restart shell."
