#!/usr/bin/env bash

OS=$(uname -s)
REPO="$(dirname $0)/.."
pushd $REPO
git submodule update --init --recursive
if [ $(uname -s) = "Darwin" ]; then
    echo "Install OSX defaults"
    source ./bootstrap/brew
else
    # assuming Debian based for now.
    echo "Install Linux defaults"

    sudo apt update
    cat apt | xargs sudo apt install
fi

# Backs up old files
[ -f ~/.zshrc ] && [ ! -f ~/.zshrc.local ] && mv ~/.zshrc ~/.zshrc.local
[ -f ~/.gitconfig ] && [ ! -f ~/.gitconfig.local ] && mv ~/.gitconfig ~/.gitconfig.local
[ -f ~/.tmux.conf ] && [ ! -f ~/.tmux.conf.local ] && mv ~/.tmux ~/.tmux.conf.local


echo "Running rcup, make take a few minutes..."
rcup
popd

echo "Install Rust libraries"
cat cargo | xargs cargo install

echo "Install NPM libraries"
cat npm | xargs npm -g install

echo "finished! restart shell."
