alias gu='git reset HEAD --'
alias gdiscard='git checkout --'
alias gbls='git for-each-ref --sort=committerdate refs/heads/ --format="%(color: red)%(committerdate:short) %(color: cyan)%(refname:short)" | ag -v "(\/save/|jb\/foo|master|main)"'
alias gblsa='git for-each-ref --sort=committerdate refs/heads/ --format="%(color: red)%(committerdate:short) %(color: cyan)%(refname:short)"'
alias gdc='git diff --cached'
alias gdt='git difftool -t Kaleidoscope'
alias gdtc='git difftool -t Kaleidoscope --cached'
alias glone='git log --pretty=format:"%h%x09%<(30)%ae%<(35)%aD%x09%s"' # %x09%an
alias glol='git log --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr)%Creset by %C(bold blue)%an%Creset %C(bold blue)<%ae>%Creset"'
alias glom='git pull origin master'
alias gbc='git branch -r --contains'
alias wip='git add . && git stash save'