[global]
    target = "~/bin"

["ast-grep/ast-grep"]
["atuinsh/atuin"]
    asset_filters = ["^update"]
["sharkdp/bat"]
    asset_filters = ["^gnu"]
["theryangeary/choose"]
    asset_filters = ["^gnu"]
["comby-tools/comby"]
    asset_filters = ["^.tar.gz"]
["dandavison/delta"]
    asset_filters = ["^gnu"]
["eza-community/eza"]
    asset_filters = ["gnu.tar.gz", "^windows", "^aarch64"]
["sharkdp/fd"]
    asset_filters = ["^gnu"]
["charmbracelet/gum"]
    asset_filters = ["^.sbom.json"]
["jqlang/jq"]
    asset_filters = ["^linux64"]
["jesseduffield/lazygit"]
["nushell/nushell"]
    asset_filters = ["^gnu"]
    file = "nu"
["boyter/scc"]
["chmln/sd"]
    asset_filters = ["^gnu"]
["starship/starship"]
    asset_filters = ["^gnu", "^.pkg"]
["ajeetdsouza/zoxide"]
