onboarding = false

[advanced]
scrollback_limit_bytes = 100000000 # 100 MB

[experimental]
pane_history = true

[keys]
prefix = "ctrl+a"
goto = "prefix+g"
new_tab = "prefix+c"
next_tab = "prefix+n"
previous_tab = "prefix+p"
focus_pane_left = "prefix+left"
focus_pane_right = "prefix+right"
focus_pane_up = "prefix+up"
focus_pane_down = "prefix+down"
navigate_workspace_down = "down"
navigate_pane_down = "ctrl+down"
rename_tab = "prefix+comma"
split_horizontal = "prefix+minus"
split_vertical = "prefix+shift+backslash"
switch_tab = "prefix+1..9"
switch_workspace = "prefix+shift+1..9"

[terminal]
default_shell = "zsh"
shell_mode = "login"

[ui]
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = false

[ui.sidebar.agents]
rows = [
  ["state_icon", "workspace", "tab"],
  ["state_text", "agent"],
]

[ui.sound]
enabled = false

[ui.toast]
delivery = "terminal"
delay_seconds = 1
